### PR TITLE
More testing

### PR DESCRIPTION
**Pull request by pablobm**
While I try diagnose something else, this PR adds two helps to development:

* Adds a root route, so that the `administratre-0.13` appraisal passes tests, which are breaking currently.
* Tests the "edit" and "update" cases, which are test-less at the moment.

### CODE REVIEW

**Comment by pablobm** [comment]
Also, it looks like tests and linter are not running for PRs?

**Comment by nickcharlton** [comment]
I'm having a look at Circle. This is the second time it's happened to me on a project in a few weeks (😒).

**Comment by nickcharlton** [comment]
Okay, third time re-adding lucky. Can you push a commit and see if it works?

**Comment by pablobm** [comment]
@nickcharlton - No dice. First I tried by changing the order of the commits and force-pushing. Then I tried adding an extranous file in a new commit. Neither worked :-(

**Comment by nickcharlton** [comment]
I bet that it won't show up on this PR but will on subsequent ones. I kicked off a build on `master` so let's see if that works: https://app.circleci.com/pipelines/github/nickcharlton/administrate-field-nested_has_many/27/workflows/fd4bc88a-c3c6-48d5-8972-e75e7f343b0e

**Comment by pablobm** [comment]
I'll try by closing this PR and opening a new one.

**Pull request closed without merging**
