### PR TITLE
Add support for attribute grouping

### LINKED ISSUE #65: Incompatibility with attribute grouping (Administrate 0.20.0)
The latest version of Administrate [groups attributes](https://github.com/thoughtbot/administrate/pull/2422). 
The return value for `Field#attributes` is now a `Hash` `{"Group title" => [Field, Field]}` rather than an `Array` `[Field, Field]`. **This is incompatible with the current version**, throwing `Undefined method 'attributes' for "":String (NoMethodError)` where `""` is the group title.

[This is where](https://github.com/nickcharlton/administrate-field-nested_has_many/blob/94500b6355a291f3ae604333561f1b3e0b57df10/lib/administrate/field/nested_has_many.rb#L29-L33) the error is first raised:
```
# lib/administrate/field/nested_has_many.rb

  def nested_fields
    associated_form.attributes.reject do |nested_field|
      skipped_fields.include?(nested_field.attribute)
    end
  end
  ```
  
  I may be able to make a PR to handle the new format but in the meantime I wanted to document my findings.

### PR DESCRIPTION
**Pull request by trevorrjohn**
In Administrate v0.20.0, support was added for grouping fields but this was not compatible with this field type.

Recreates https://github.com/nickcharlton/administrate-field-nested_has_many/pull/66

Fixes #65

### CODE REVIEW

**Comment by trevorrjohn** [comment]
@nickcharlton sorry, I renamed master to main and it auto closed the PR. I couldn't figure out how to re-open it and change the branch name.

**Comment by HuntBurdick** [comment]
I'm using this branch so I can use the latest administrate gem version and everything seems to be working well until I hit a validation error. If I hit the validation error with a new record, any in progress values are persisted and repainted to the form but if there is a validation error on an existing record, all in progress values are lost and not repainted to the form. I have been debugging this all day and I'm at a bit of a loss. This is a big blocker for me and will be debugging until I find a solution. Does this happen for you as well?

**Comment by HuntBurdick** [comment]
Ah looks like it's something with my implementation. Did a fresh install and this issue does not exist out of box. I'm suspecting the friendly ID gem I'm using might be interfering. Please disregard, thanks.

**Comment by nickcharlton** [comment]
Thanks for checking back in, @HuntBurdick. If there are specific issues with this gem/Administrate itself, please open a new issue if you come across them!

**Comment by gustavosobral** [comment]
@nickcharlton are you planning to make a new release that cover this change soon? Just this bug is blocking our update to the latest `administrate`

**Comment by nickcharlton** [comment]
Oh! …yes, I should. I'll do that as soon as I can, I'm not aware of anything which should hold us back.

**Comment by nickcharlton** [comment]
I've just [released v2.1.0](https://github.com/nickcharlton/administrate-field-nested_has_many/releases/tag/v2.1.0) which means this is now released. Thanks everyone!

**Pull request merged**
