### PR TITLE
Let Administrate figure out the associations

### PR DESCRIPTION
**Pull request by pablobm**
Following https://github.com/thoughtbot/administrate/pull/1633, this PR would bring this plugin to take advantage of Administrate's own association detection, doing away with the `:class_name` option.

Note that this breaks compatibility with versions of Administrate prior to 0.15.

### CODE REVIEW

**Comment by pablobm** [comment]
Uh, CircleCI doesn't appear to be using Administrate `master`? Hm, not a big issue for now I guess.

**Comment by nickcharlton** [comment]
Is the CI problem because of Appraisal? A thought here: we could point an Appraisal set to `master`, and just let the rest fail until it's updated upstream.

As for breaking changes: I think we're okay there, we'll just need to make a note in the CHANGELOG when we release.

**Comment by pablobm** [comment]
Oh, I forgot about Appraisal. You are right, it works after removing the appraisals for old versions. So either this is merged without back compatibility, or I spend a bit more time to make it work with older versions.

By the way, we already have some code to do back compatibility. If we are merging as is, we probably should also remove that:

https://github.com/nickcharlton/administrate-field-nested_has_many/blob/bc1c881c968f716d5435d3f594f25abf4c1c281d/app/views/fields/nested_has_many/_show.html.erb#L1-L9

Perhaps we can wait for the next version of Administrate and I'll do two PRs: one to remove compatibility with older versions, and another would be this PR.

**Comment by pablobm** [comment]
As mentioned I have opened PR https://github.com/nickcharlton/administrate-field-nested_has_many/pull/46, which will remove the compatibility with Administrate prior to v0.10

**Comment by pablobm** [comment]
Took this PR out of draft mode. I think this can be considered for merge now.

**Review by nickcharlton — APPROVED** [review]

**Pull request merged**
